AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Udagram is a social networking application that runs on the AWS infrastructure. This CloudFormation template installs network and server infrastructure for the Udagram application.
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to the resources used by the Udagram 
    application
    Type: String
  VpcCIDR:
    Description: 
    Type: